embedding_list = [('test-id', 'Test009BlocksAndModels', {'line_no': 1, 'file_name': 'Test009BlocksAndModels.rhino'}),
('test-scenario', 'verify that new project created when create a new project using the user interface', {'line_no': 2, 'file_name': 'Test009BlocksAndModels.rhino'}),
('test-priority', '1 - critical', {'line_no': 3, 'file_name': 'Test009BlocksAndModels.rhino'}),
('test-severity', '1 - critical', {'line_no': 4, 'file_name': 'Test009BlocksAndModels.rhino'}),
('test-tolerance', '0%', {'line_no': 5, 'file_name': 'Test009BlocksAndModels.rhino'}),
('test-actions', '', {'line_no': 7, 'file_name': 'Test009BlocksAndModels.rhino'}),
('test-actions-1', 'go to url {open-project application}', {'line_no': 8, 'file_name': 'Test009BlocksAndModels.rhino'}),
('test-actions-2', 'login to open project  using arguments   user=open-project user name AND password=open-project password on element using css selector from attribute filter regex', {'line_no': 9, 'file_name': 'Test009BlocksAndModels.rhino'}),
('test-actions-3', 'create default project  using arguments   name=unique project name AND description=Created by Automation Script', {'line_no': 10, 'file_name': 'Test009BlocksAndModels.rhino'}),
('test-actions-4', 'set project status  using arguments   status=On track', {'line_no': 11, 'file_name': 'Test009BlocksAndModels.rhino'}),
('test-actions-5', 'click on {work packages menu}', {'line_no': 12, 'file_name': 'Test009BlocksAndModels.rhino'}),
('test-actions-6', 'close browser', {'line_no': 13, 'file_name': 'Test009BlocksAndModels.rhino'}),
('test-expected-results', '', {'line_no': 15, 'file_name': 'Test009BlocksAndModels.rhino'}),
('5', 'verify that {exists} status of {project menu} equal {true}', {'line_no': 16, 'file_name': 'Test009BlocksAndModels.rhino'})]